package com.monssef.ecommerce.category;

import com.monssef.ecommerce.common.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

@Service
@RequiredArgsConstructor            // constructor injection (generated by Lombok)
@Transactional(readOnly = true)     // read-only transaction by default
public class CategoryService {

    private final CategoryRepository repository;

    public List<Category> findAll() {
        return repository.findAll();
    }

    public Category findById(Long id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Category", id));
    }

    @Transactional
    public Category create(Category category) {
        if (repository.existsByNameIgnoreCase(category.getName())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Category already exists: " + category.getName());
        }
        category.setId(null); // ignore any id sent by the client
        return repository.save(category);
    }

    @Transactional
    public Category update(Long id, Category data) {
        Category category = findById(id);
        boolean nameChanged = !category.getName().equalsIgnoreCase(data.getName());
        if (nameChanged && repository.existsByNameIgnoreCase(data.getName())) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Category already exists: " + data.getName());
        }
        category.setName(data.getName());
        category.setDescription(data.getDescription());
        return category; // managed entity: Hibernate saves the changes at commit
    }

    @Transactional
    public void delete(Long id) {
        Category category = findById(id);
        try {
            repository.delete(category);
            repository.flush(); // runs the DELETE now so a foreign key violation is detected here
        } catch (DataIntegrityViolationException e) {
            throw new ResponseStatusException(HttpStatus.CONFLICT,
                    "Category is still used by products");
        }
    }
}
